// <auto-generated />
using System;
using InventoryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InventoryManagement.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200423024609_AllTable")]
    partial class AllTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InventoryManagement.Data.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double>("Due")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float")
                        .HasComputedColumnSql("(([TotalAmount]+[ReturnAmount])-([TotalDiscount]+[Paid]))");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<double>("Paid")
                        .HasColumnType("float");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<double>("ReturnAmount")
                        .HasColumnType("float");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<double>("TotalDiscount")
                        .HasColumnType("float");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("InventoryManagement.Data.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ExpenseAmount")
                        .HasColumnType("float");

                    b.Property<int>("ExpenseCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpenseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ExpenseFor")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("ExpensePaymentMethod")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.HasKey("ExpenseId");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Expense");
                });

            modelBuilder.Entity("InventoryManagement.Data.ExpenseCategory", b =>
                {
                    b.Property<int>("ExpenseCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<double>("TotalExpense")
                        .HasColumnType("float");

                    b.HasKey("ExpenseCategoryId");

                    b.ToTable("ExpenseCategory");
                });

            modelBuilder.Entity("InventoryManagement.Data.Institution", b =>
                {
                    b.Property<int>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("DialogTitle")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Established")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<byte[]>("InstitutionLogo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("LocalArea")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("InstitutionId");

                    b.ToTable("Institution");

                    b.HasData(
                        new
                        {
                            InstitutionId = 1,
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstitutionName = "Institution"
                        });
                });

            modelBuilder.Entity("InventoryManagement.Data.PageLink", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<int>("LinkCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<int?>("Sn")
                        .HasColumnName("SN")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("LinkId");

                    b.HasIndex("LinkCategoryId");

                    b.ToTable("PageLink");
                });

            modelBuilder.Entity("InventoryManagement.Data.PageLinkAssign", b =>
                {
                    b.Property<int>("LinkAssignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LinkId")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.HasKey("LinkAssignId");

                    b.HasIndex("LinkId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("PageLinkAssign");
                });

            modelBuilder.Entity("InventoryManagement.Data.PageLinkCategory", b =>
                {
                    b.Property<int>("LinkCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<int?>("Sn")
                        .HasColumnName("SN")
                        .HasColumnType("int");

                    b.HasKey("LinkCategoryId");

                    b.ToTable("PageLinkCategory");
                });

            modelBuilder.Entity("InventoryManagement.Data.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ProductCatalogId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<double>("PurchasePrice")
                        .HasColumnType("float");

                    b.Property<double>("SellingPrice")
                        .HasColumnType("float");

                    b.Property<string>("Warranty")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("ProductId");

                    b.HasIndex("ProductCatalogId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("InventoryManagement.Data.ProductCatalog", b =>
                {
                    b.Property<int>("ProductCatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CatalogLevel")
                        .HasColumnType("int");

                    b.Property<string>("CatalogName")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("CatalogTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("ProductCatalogId");

                    b.HasIndex("CatalogTypeId");

                    b.HasIndex("ParentId");

                    b.ToTable("ProductCatalog");
                });

            modelBuilder.Entity("InventoryManagement.Data.ProductCatalogType", b =>
                {
                    b.Property<int>("CatalogTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CatalogType")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("CatalogTypeId");

                    b.ToTable("ProductCatalogType");
                });

            modelBuilder.Entity("InventoryManagement.Data.ProductStock", b =>
                {
                    b.Property<int>("ProductStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductStockId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductStock");
                });

            modelBuilder.Entity("InventoryManagement.Data.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("PurchaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<double>("PurchaseDiscountAmount")
                        .HasColumnType("float");

                    b.Property<double>("PurchaseDiscountPercentage")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float")
                        .HasComputedColumnSql("(case when [PurchaseTotalPrice]=(0) then (0) else round(([PurchaseDiscountAmount]*(100))/[PurchaseTotalPrice],(2)) end)");

                    b.Property<double>("PurchaseDueAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float")
                        .HasComputedColumnSql("(round(([PurchaseTotalPrice]+[PurchaseReturnAmount])-([PurchaseDiscountAmount]+[PurchasePaidAmount]),(2)))");

                    b.Property<double>("PurchasePaidAmount")
                        .HasColumnType("float");

                    b.Property<string>("PurchasePaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(4)")
                        .HasComputedColumnSql("(case when (([PurchaseTotalPrice]+[PurchaseReturnAmount])-([PurchaseDiscountAmount]+[PurchasePaidAmount]))<=(0) then 'Paid' else 'Due' end)")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<double>("PurchaseReturnAmount")
                        .HasColumnType("float");

                    b.Property<int>("PurchaseSn")
                        .HasColumnName("PurchaseSN")
                        .HasColumnType("int");

                    b.Property<double>("PurchaseTotalPrice")
                        .HasColumnType("float");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("PurchaseId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("VendorId");

                    b.ToTable("Purchase");
                });

            modelBuilder.Entity("InventoryManagement.Data.PurchaseAdjustment", b =>
                {
                    b.Property<int>("PurchaseAdjustmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdjustmentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int");

                    b.HasKey("PurchaseAdjustmentId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseAdjustment");
                });

            modelBuilder.Entity("InventoryManagement.Data.PurchasePayment", b =>
                {
                    b.Property<int>("PurchasePaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<double>("PaidAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaidDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("ReceiptSn")
                        .HasColumnName("ReceiptSN")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("PurchasePaymentId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("VendorId");

                    b.ToTable("PurchasePayment");
                });

            modelBuilder.Entity("InventoryManagement.Data.PurchasePaymentList", b =>
                {
                    b.Property<int>("PurchasePaymentListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<double>("PurchasePaidAmount")
                        .HasColumnType("float");

                    b.Property<int>("PurchasePaymentId")
                        .HasColumnType("int");

                    b.HasKey("PurchasePaymentListId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("PurchasePaymentId");

                    b.ToTable("PurchasePaymentList");
                });

            modelBuilder.Entity("InventoryManagement.Data.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DateofBirth")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("NationalId")
                        .HasColumnName("NationalID")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Ps")
                        .HasColumnName("PS")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool?>("Validation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("RegistrationId");

                    b.ToTable("Registration");

                    b.HasData(
                        new
                        {
                            RegistrationId = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Admin",
                            Ps = "Admin_121",
                            Type = "Admin",
                            UserName = "Admin",
                            Validation = true
                        });
                });

            modelBuilder.Entity("InventoryManagement.Data.Selling", b =>
                {
                    b.Property<int>("SellingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SellingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<double>("SellingDiscountAmount")
                        .HasColumnType("float");

                    b.Property<double>("SellingDiscountPercentage")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float")
                        .HasComputedColumnSql("(case when [SellingTotalPrice]=(0) then (0) else round(([SellingDiscountAmount]*(100))/[SellingTotalPrice],(2)) end)");

                    b.Property<double>("SellingDueAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float")
                        .HasComputedColumnSql("(round(([SellingTotalPrice]+[SellingReturnAmount])-([SellingDiscountAmount]+[SellingPaidAmount]),(2)))");

                    b.Property<double>("SellingPaidAmount")
                        .HasColumnType("float");

                    b.Property<string>("SellingPaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(4)")
                        .HasComputedColumnSql("(case when (([SellingTotalPrice]+[SellingReturnAmount])-([SellingDiscountAmount]+[SellingPaidAmount]))<=(0) then 'Paid' else 'Due' end)")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<double>("SellingReturnAmount")
                        .HasColumnType("float");

                    b.Property<int>("SellingSn")
                        .HasColumnName("SellingSN")
                        .HasColumnType("int");

                    b.Property<double>("SellingTotalPrice")
                        .HasColumnType("float");

                    b.HasKey("SellingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Selling");
                });

            modelBuilder.Entity("InventoryManagement.Data.SellingAdjustment", b =>
                {
                    b.Property<int>("SellingAdjustmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdjustmentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductStockId")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<int>("SellingId")
                        .HasColumnType("int");

                    b.HasKey("SellingAdjustmentId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductStockId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("SellingId");

                    b.ToTable("SellingAdjustment");
                });

            modelBuilder.Entity("InventoryManagement.Data.SellingList", b =>
                {
                    b.Property<int>("SellingListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductStockId")
                        .HasColumnType("int");

                    b.Property<int>("SellingId")
                        .HasColumnType("int");

                    b.Property<double>("SellingPrice")
                        .HasColumnType("float");

                    b.HasKey("SellingListId");

                    b.HasIndex("ProductStockId");

                    b.HasIndex("SellingId");

                    b.ToTable("SellingList");
                });

            modelBuilder.Entity("InventoryManagement.Data.SellingPayment", b =>
                {
                    b.Property<int>("SellingPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<double>("PaidAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaidDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("ReceiptSn")
                        .HasColumnName("ReceiptSN")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.HasKey("SellingPaymentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("SellingPayment");
                });

            modelBuilder.Entity("InventoryManagement.Data.SellingPaymentList", b =>
                {
                    b.Property<int>("SellingPaymentListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SellingId")
                        .HasColumnType("int");

                    b.Property<double>("SellingPaidAmount")
                        .HasColumnType("float");

                    b.Property<int>("SellingPaymentId")
                        .HasColumnType("int");

                    b.HasKey("SellingPaymentListId");

                    b.HasIndex("SellingId");

                    b.HasIndex("SellingPaymentId");

                    b.ToTable("SellingPaymentList");
                });

            modelBuilder.Entity("InventoryManagement.Data.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ServiceDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<double>("ServiceDiscountAmount")
                        .HasColumnType("float");

                    b.Property<double>("ServiceDiscountPercentage")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float")
                        .HasComputedColumnSql("(case when [ServiceTotalPrice]=(0) then (0) else round(([ServiceDiscountAmount]*(100))/[ServiceTotalPrice],(2)) end)");

                    b.Property<double>("ServiceDueAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float")
                        .HasComputedColumnSql("(round([ServiceTotalPrice]-([ServiceDiscountAmount]+[ServicePaidAmount]),(2)))");

                    b.Property<double>("ServicePaidAmount")
                        .HasColumnType("float");

                    b.Property<string>("ServicePaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(4)")
                        .HasComputedColumnSql("(case when ([ServiceTotalPrice]-([ServiceDiscountAmount]+[ServicePaidAmount]))<=(0) then 'Paid' else 'Due' end)")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<int>("ServiceSn")
                        .HasColumnName("ServiceSN")
                        .HasColumnType("int");

                    b.Property<double>("ServiceTotalPrice")
                        .HasColumnType("float");

                    b.HasKey("ServiceId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("InventoryManagement.Data.ServiceDevice", b =>
                {
                    b.Property<int>("ServiceDeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ProductCatalogId")
                        .HasColumnType("int");

                    b.HasKey("ServiceDeviceId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductCatalogId");

                    b.ToTable("ServiceDevice");
                });

            modelBuilder.Entity("InventoryManagement.Data.ServiceList", b =>
                {
                    b.Property<int>("ServiceListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Problem")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<double>("ServiceCharge")
                        .HasColumnType("float");

                    b.Property<int>("ServiceDeviceId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("ServiceListId");

                    b.HasIndex("ServiceDeviceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceList");
                });

            modelBuilder.Entity("InventoryManagement.Data.ServicePaymentList", b =>
                {
                    b.Property<int>("ServicePaymentListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SellingPaymentId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<double>("ServicePaidAmount")
                        .HasColumnType("float");

                    b.HasKey("ServicePaymentListId");

                    b.HasIndex("SellingPaymentId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServicePaymentList");
                });

            modelBuilder.Entity("InventoryManagement.Data.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Due")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float")
                        .HasComputedColumnSql("(([TotalAmount]+[ReturnAmount])-([TotalDiscount]+[Paid]))");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<double>("Paid")
                        .HasColumnType("float");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<double>("ReturnAmount")
                        .HasColumnType("float");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<double>("TotalDiscount")
                        .HasColumnType("float");

                    b.Property<string>("VendorAddress")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("VendorCompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("VendorName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("VendorPhone")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("VendorId");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "837d221e-3d39-4651-b239-66e68d57edb2",
                            ConcurrencyStamp = "c6d562f5-ba4f-4520-9394-792a5f25c409",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "1de93e58-ab8f-4500-8e41-f73d0d9a4edf",
                            ConcurrencyStamp = "0145818c-8cc2-455c-b5ef-2ff6f9864252",
                            Name = "sub-admin",
                            NormalizedName = "SUB-ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "24bca771-762d-457c-8aff-cdd661803190",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "541754d1-3242-44e1-92a5-b1912e7e62b1",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEHghrQ379+HRhnNR7BTluhOFOY8aUpxUZnxbb5mlwDDQxQvhfiQYBJRWIkxZ5dFvGg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "24bca771-762d-457c-8aff-cdd661803190",
                            RoleId = "837d221e-3d39-4651-b239-66e68d57edb2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("InventoryManagement.Data.Expense", b =>
                {
                    b.HasOne("InventoryManagement.Data.ExpenseCategory", "ExpenseCategory")
                        .WithMany("Expense")
                        .HasForeignKey("ExpenseCategoryId")
                        .HasConstraintName("FK_Expense_ExpenseCategory")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Registration", "Registration")
                        .WithMany("Expense")
                        .HasForeignKey("RegistrationId")
                        .HasConstraintName("FK_Expense_Registration")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.PageLink", b =>
                {
                    b.HasOne("InventoryManagement.Data.PageLinkCategory", "LinkCategory")
                        .WithMany("PageLink")
                        .HasForeignKey("LinkCategoryId")
                        .HasConstraintName("FK_PageLink_PageLinkCategory")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.PageLinkAssign", b =>
                {
                    b.HasOne("InventoryManagement.Data.PageLink", "Link")
                        .WithMany("PageLinkAssign")
                        .HasForeignKey("LinkId")
                        .HasConstraintName("FK_PageLinkAssign_PageLink")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Registration", "Registration")
                        .WithMany("PageLinkAssign")
                        .HasForeignKey("RegistrationId")
                        .HasConstraintName("FK_PageLinkAssign_Registration")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.Product", b =>
                {
                    b.HasOne("InventoryManagement.Data.ProductCatalog", "ProductCatalog")
                        .WithMany("Product")
                        .HasForeignKey("ProductCatalogId")
                        .HasConstraintName("FK_Product_ProductCatalog")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Purchase", "Purchase")
                        .WithMany("Product")
                        .HasForeignKey("PurchaseId")
                        .HasConstraintName("FK_Product_Purchase")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.ProductCatalog", b =>
                {
                    b.HasOne("InventoryManagement.Data.ProductCatalogType", "CatalogType")
                        .WithMany("ProductCatalog")
                        .HasForeignKey("CatalogTypeId")
                        .HasConstraintName("FK_ProductCatalog_ProductCatalogType");

                    b.HasOne("InventoryManagement.Data.ProductCatalog", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_ProductCatalog_ProductCatalog")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.ProductStock", b =>
                {
                    b.HasOne("InventoryManagement.Data.Product", "Product")
                        .WithMany("ProductStock")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_ProductStock_Product")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.Purchase", b =>
                {
                    b.HasOne("InventoryManagement.Data.Registration", "Registration")
                        .WithMany("Purchase")
                        .HasForeignKey("RegistrationId")
                        .HasConstraintName("FK_Purchase_Registration")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Vendor", "Vendor")
                        .WithMany("Purchase")
                        .HasForeignKey("VendorId")
                        .HasConstraintName("FK_Purchase_Vendor")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.PurchaseAdjustment", b =>
                {
                    b.HasOne("InventoryManagement.Data.Product", "Product")
                        .WithMany("PurchaseAdjustment")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_PurchaseAdjustment_Product")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Purchase", "Purchase")
                        .WithMany("PurchaseAdjustment")
                        .HasForeignKey("PurchaseId")
                        .HasConstraintName("FK_PurchaseAdjustment_Purchase")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.PurchasePayment", b =>
                {
                    b.HasOne("InventoryManagement.Data.Registration", "Registration")
                        .WithMany("PurchasePayment")
                        .HasForeignKey("RegistrationId")
                        .HasConstraintName("FK_PurchasePayment_Registration")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Vendor", "Vendor")
                        .WithMany("PurchasePayment")
                        .HasForeignKey("VendorId")
                        .HasConstraintName("FK_PurchasePayment_Vendor")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.PurchasePaymentList", b =>
                {
                    b.HasOne("InventoryManagement.Data.Purchase", "Purchase")
                        .WithMany("PurchasePaymentList")
                        .HasForeignKey("PurchaseId")
                        .HasConstraintName("FK_PurchasePaymentList_Purchase")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.PurchasePayment", "PurchasePayment")
                        .WithMany("PurchasePaymentList")
                        .HasForeignKey("PurchasePaymentId")
                        .HasConstraintName("FK_PurchasePaymentList_PurchasePayment")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.Selling", b =>
                {
                    b.HasOne("InventoryManagement.Data.Customer", "Customer")
                        .WithMany("Selling")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Selling_Customer")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Registration", "Registration")
                        .WithMany("Selling")
                        .HasForeignKey("RegistrationId")
                        .HasConstraintName("FK_Selling_Registration")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.SellingAdjustment", b =>
                {
                    b.HasOne("InventoryManagement.Data.Product", "Product")
                        .WithMany("SellingAdjustment")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_SellingAdjustment_Product")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.ProductStock", "ProductStock")
                        .WithMany("SellingAdjustment")
                        .HasForeignKey("ProductStockId")
                        .HasConstraintName("FK_SellingAdjustment_ProductStock")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Registration", "Registration")
                        .WithMany("SellingAdjustment")
                        .HasForeignKey("RegistrationId")
                        .HasConstraintName("FK_SellingAdjustment_Registration")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Selling", "Selling")
                        .WithMany("SellingAdjustment")
                        .HasForeignKey("SellingId")
                        .HasConstraintName("FK_SellingAdjustment_Selling")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.SellingList", b =>
                {
                    b.HasOne("InventoryManagement.Data.ProductStock", "ProductStock")
                        .WithMany("SellingList")
                        .HasForeignKey("ProductStockId")
                        .HasConstraintName("FK_SellingList_ProductStock")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Selling", "Selling")
                        .WithMany("SellingList")
                        .HasForeignKey("SellingId")
                        .HasConstraintName("FK_SellingList_Selling")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.SellingPayment", b =>
                {
                    b.HasOne("InventoryManagement.Data.Customer", "Customer")
                        .WithMany("SellingPayment")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_SellingPayment_Customer")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Registration", "Registration")
                        .WithMany("SellingPayment")
                        .HasForeignKey("RegistrationId")
                        .HasConstraintName("FK_SellingPayment_Registration")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.SellingPaymentList", b =>
                {
                    b.HasOne("InventoryManagement.Data.Selling", "Selling")
                        .WithMany("SellingPaymentList")
                        .HasForeignKey("SellingId")
                        .HasConstraintName("FK_SellingPaymentList_Selling")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.SellingPayment", "SellingPayment")
                        .WithMany("SellingPaymentList")
                        .HasForeignKey("SellingPaymentId")
                        .HasConstraintName("FK_SellingPaymentList_SellingPayment")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.Service", b =>
                {
                    b.HasOne("InventoryManagement.Data.Customer", "Customer")
                        .WithMany("Service")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Service_Customer")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Registration", "Registration")
                        .WithMany("Service")
                        .HasForeignKey("RegistrationId")
                        .HasConstraintName("FK_Service_Registration")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.ServiceDevice", b =>
                {
                    b.HasOne("InventoryManagement.Data.Customer", "Customer")
                        .WithMany("ServiceDevice")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_ServiceDevice_Customer")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.ProductCatalog", "ProductCatalog")
                        .WithMany("ServiceDevice")
                        .HasForeignKey("ProductCatalogId")
                        .HasConstraintName("FK_ServiceDevice_ProductCatalog")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.ServiceList", b =>
                {
                    b.HasOne("InventoryManagement.Data.ServiceDevice", "ServiceDevice")
                        .WithMany("ServiceList")
                        .HasForeignKey("ServiceDeviceId")
                        .HasConstraintName("FK_ServiceList_ServiceDevice")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Service", "Service")
                        .WithMany("ServiceList")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_ServiceList_Service")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Data.ServicePaymentList", b =>
                {
                    b.HasOne("InventoryManagement.Data.SellingPayment", "SellingPayment")
                        .WithMany("ServicePaymentList")
                        .HasForeignKey("SellingPaymentId")
                        .HasConstraintName("FK_ServicePaymentList_SellingPayment")
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Service", "Service")
                        .WithMany("ServicePaymentList")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_ServicePaymentList_Service")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
